version: 2.1


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
jobs:
  build:
    working_directory: ~/deploy-test-app
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - run: ruby --version
      

      - restore_cache:
          keys: gem-cache-{{ checksum "Gemfile.lock"}}
                gem-cache-
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock"}} 
          paths:
           - vendor/bundle

      - run:
          name: set up database
          command: |
            rake db:create
            rake db:schema:load

  deploy:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\";export PRIVATE_KEY=\"$PRIVATE_KEY\"; rm -rf deploy-test-app/ ; git clone https://github.com/DenisOReganCloudAppDev/deploy-test-app.git ; source deploy-test-app/deploy.sh"