version: 2.1


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      

      - restore_cache:
          keys: gem-cache-{{ checksum "Gemfile.lock"}}
                gem-cache-
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock"}} 
          paths:
           - vendor/bundle

      - run:
          name: set up database
          command: |
            rails db:create
            rails db:schema:load

